//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionSkane.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikelgrupp
    {
        public string C22Artikelgrupp { get; set; }
        public string namn { get; set; }
        public string C21Varugrupp { get; set; }
        public string C20Huvudgrupp { get; set; }
    
        public virtual Varugrupp Varugrupp { get; set; }
    }
}
