//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionSkane.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leverantör
    {
        public double Leverantörnr { get; set; }
        public string Namn { get; set; }
        public Nullable<double> Org__Nr_ { get; set; }
        public string Leverantörsnamn { get; set; }
        public string Adress { get; set; }
        public string Postkod___Ort { get; set; }
        public string Telefon_nr { get; set; }
        public string Faxnr { get; set; }
    }
}
