//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionSkane.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReSkEntities : DbContext
    {
        public ReSkEntities()
            : base("name=ReSkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikelgrupp> Artikelgrupp { get; set; }
        public virtual DbSet<Avtal> Avtal { get; set; }
        public virtual DbSet<Handläggare> Handläggare { get; set; }
        public virtual DbSet<Huvudgrupp> Huvudgrupp { get; set; }
        public virtual DbSet<Leverantör> Leverantör { get; set; }
        public virtual DbSet<Varugrupp> Varugrupp { get; set; }
    }
}
