//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionSkane.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public Artikel()
        {
            this.Avtal = new HashSet<Avtal>();
        }
    
        public string C01Artikelnr_RS { get; set; }
        public string C06Benämning_1 { get; set; }
        public string C07Benämning_2 { get; set; }
        public string C08ProdNamn { get; set; }
        public string C09LevArtNr { get; set; }
        public string C10LevNr { get; set; }
        public string C12MBE_Lev { get; set; }
        public string C13MBE_Kund { get; set; }
        public string C14TrspFp { get; set; }
        public string C15PallFp { get; set; }
        public string C16Enhet { get; set; }
        public string C17PrisPerEnhet { get; set; }
        public string C18Momssats { get; set; }
        public string C19Regions_kod { get; set; }
        public string C22Artikelgrupp { get; set; }
        public string C23Lagertyp { get; set; }
        public string C24Ledtid_Lev { get; set; }
        public string C25BerFörbr { get; set; }
        public string C26ÄndrBeskr { get; set; }
        public string C27Reg__art_konto { get; set; }
        public string C28Ändringshändelse { get; set; }
        public string C29Avtalsnr { get; set; }
        public string C30Lagerställe_Krav { get; set; }
        public string C31Mrp_kod { get; set; }
        public string Pos__Nr { get; set; }
        public string Tillv__Land { get; set; }
        public string Valuta { get; set; }
        public string Avd__Fp { get; set; }
        public string Anmärkningar { get; set; }
        public string Produktleverantör { get; set; }
    
        public virtual Leverantör Leverantör { get; set; }
        public virtual Artikelgrupp Artikelgrupp { get; set; }
        public virtual ICollection<Avtal> Avtal { get; set; }
        public virtual Avtal Avtal1 { get; set; }
    }
}
