//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionSkane.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtal
    {
        public Avtal()
        {
            this.Artikel1 = new HashSet<Artikel>();
        }
    
        public string C29Avtalsnr { get; set; }
        public string C01Artikelnr_RS { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual ICollection<Artikel> Artikel1 { get; set; }
    }
}
