//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionSkane.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huvudgrupp
    {
        public Huvudgrupp()
        {
            this.Varugrupp = new HashSet<Varugrupp>();
        }
    
        public string C20Huvudgrupp { get; set; }
        public string HuvudgruppsNamn { get; set; }
    
        public virtual ICollection<Varugrupp> Varugrupp { get; set; }
    }
}
